# Generated by Django 4.2.1 on 2023-05-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Navigation", "0002_videobucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                (
                    "size",
                    models.CharField(
                        choices=[("small", "Small"), ("large", "Large")], max_length=10
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "userphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Navigation.videobucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(blank=True, null=True)),
                ("text2", models.TextField(blank=True, null=True)),
                ("Buttontext3", models.TextField(blank=True, null=True)),
                ("Buttontext4", models.TextField(blank=True, null=True)),
                ("text5", models.TextField(blank=True, null=True)),
                ("text6", models.TextField(blank=True, null=True)),
                ("text7", models.TextField(blank=True, null=True)),
                ("Buttontext8", models.TextField(blank=True, null=True)),
                ("Buttontext9", models.TextField(blank=True, null=True)),
                ("text10", models.TextField(blank=True, null=True)),
                ("text11", models.TextField(blank=True, null=True)),
                ("buttontext12", models.TextField(blank=True, null=True)),
                ("buttontext13", models.TextField(blank=True, null=True)),
                ("text14", models.TextField(blank=True, null=True)),
                ("text15", models.TextField(blank=True, null=True)),
                ("text16", models.TextField(blank=True, null=True)),
                ("text17", models.TextField(blank=True, null=True)),
                ("text18", models.TextField(blank=True, null=True)),
                ("text19", models.TextField(blank=True, null=True)),
                ("text20", models.TextField(blank=True, null=True)),
                ("text21", models.TextField(blank=True, null=True)),
                ("text22", models.TextField(blank=True, null=True)),
                ("text23", models.TextField(blank=True, null=True)),
                ("text24", models.TextField(blank=True, null=True)),
                ("text25", models.TextField(blank=True, null=True)),
                ("text26", models.TextField(blank=True, null=True)),
                ("text33", models.TextField(blank=True, null=True)),
                ("text34", models.TextField(blank=True, null=True)),
                ("text35", models.TextField(blank=True, null=True)),
                ("buttontext36", models.TextField(blank=True, null=True)),
                ("buttontext37", models.TextField(blank=True, null=True)),
                ("text27", models.TextField(blank=True, null=True)),
                ("text28", models.TextField(blank=True, null=True)),
                ("text29", models.TextField(blank=True, null=True)),
                ("text38", models.TextField(blank=True, null=True)),
                ("text39", models.TextField(blank=True, null=True)),
                ("buttontext40", models.TextField(blank=True, null=True)),
                ("buttontext41", models.TextField(blank=True, null=True)),
                ("text30", models.TextField(blank=True, null=True)),
                ("text31", models.TextField(blank=True, null=True)),
                ("text32", models.TextField(blank=True, null=True)),
                ("text43", models.TextField(blank=True, null=True)),
                ("text44", models.TextField(blank=True, null=True)),
                ("buttontext45", models.TextField(blank=True, null=True)),
                ("text46", models.TextField(blank=True, null=True)),
                ("text47", models.TextField(blank=True, null=True)),
                ("text48", models.TextField(blank=True, null=True)),
                ("DailyBlogs", models.TextField(blank=True, null=True)),
                ("buttontext42", models.TextField(blank=True, null=True)),
                ("text49", models.TextField(blank=True, null=True)),
                ("text50", models.TextField(blank=True, null=True)),
                ("buttontext51", models.TextField(blank=True, null=True)),
                ("text52", models.TextField(blank=True, null=True)),
                ("text53", models.TextField(blank=True, null=True)),
                ("LearnMorebutton", models.TextField(blank=True, null=True)),
                (
                    "aboutimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_aboutimg",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "aboutimgcan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_aboutimgcan",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "afoursizeimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_afoursizeimg",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "crownimg1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_crownimg1",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "crownimg2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_crownimg2",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "crownimg3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_crownimg3",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "crownimg4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_crownimg4",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "cup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_cup",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "facebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_facebook",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "google",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_google",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "googleads",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_googleads",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "googlenetwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_googlenetwork",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "hubspot3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_hubspot3",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "soccer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_soccer",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "thumpsup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_thumpsup",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "video1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_video1",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "video2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_video2",
                        to="Navigation.mediabucket",
                    ),
                ),
                (
                    "youtubeads",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_youtubeads",
                        to="Navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detailsquestion", models.TextField()),
                ("detailsanswer", models.TextField()),
                (
                    "detailsphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
