# Generated by Django 4.2.1 on 2023-05-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Navigation", "0002_videobucket"),
        ("Homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="video1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_video1",
                to="Navigation.videobucket",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="video2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_video2",
                to="Navigation.videobucket",
            ),
        ),
    ]
