# Generated by Django 4.2.1 on 2023-05-20 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Homepage", "0002_alter_homepage_video1_alter_homepage_video2"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="watchvideo",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
