# Generated by Django 4.2.1 on 2023-05-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Navigation", "0003_rename_text2_footer_britishlogo_and_more"),
        ("Homepage", "0003_review_watchvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="text27svg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_text27svg",
                to="Navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="text28svg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_text28svg",
                to="Navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="text29svg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_text29svg",
                to="Navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video1poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_video1poster",
                to="Navigation.mediabucket",
            ),
        ),
    ]
