# Generated by Django 4.2.1 on 2023-05-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Navigation", "0003_rename_text2_footer_britishlogo_and_more"),
        ("Homepage", "0005_homepage_pencilimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="soccerblur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_soccerblur",
                to="Navigation.mediabucket",
            ),
        ),
    ]
