# Generated by Django 4.2.1 on 2023-05-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Navigation", "0002_videobucket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footer",
            old_name="text2",
            new_name="britishlogo",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text3",
            new_name="capabalities",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text4",
            new_name="copyright",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text5",
            new_name="support",
        ),
        migrations.CreateModel(
            name="Headerlogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookademo", models.TextField(blank=True, null=True)),
                (
                    "headerlogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
